### ISSUE TITLE
data structure of input files

### ISSUE THREAD

**Issue by OPopow** [Kevin-Haigis-Lab/PackageBluishgreen#6]
1. Is it possible to change the code so it would use the second and third column (now named 'DAPI_nucleiMask' and FITC_nucleiMask') irrespective of the title of these columns?
With an update of the segmentation pipeline these columns are now called simply 'DAPI' and 'FITC' or 'Cy5' (depending on the fluorescent channel used). 

2. What is the logic behind extracting the information from the .csv file name? 
- Is it necessary to include **unmicst-**OPXXX? 
- Will additions to the slide name after the slide number (e.g. OP2000_heart_DAPI-EdU_01-01**_XXX**) cause issues?

Thank you!

**Comment by jhrcook** [comment]
I think addressing this will require changes to the pipeline [bluishgreen-run](https://github.com/Kevin-Haigis-Lab/bluishgreen-run). I'm not certain for the first point, but am fairly confident for the second (because it has to do with extracting metadata from the file name – @OPopow, this is what I was talking about in the email and didn't realize the Issue was opened on this repo).

**Comment by jhrcook** [comment]
Re. the first bullet: that is also related to the pipeline, not this package. I'm going to close this issue and open two issues on the pipeline.

**Comment by jhrcook** [comment]
Linked issues:

- https://github.com/Kevin-Haigis-Lab/bluishgreen-run/issues/13
- https://github.com/Kevin-Haigis-Lab/bluishgreen-run/issues/14
